### ISSUE TITLE
Unable to use a specific axe-core with -a parameter

### ISSUE THREAD

**Issue by aarontk** [dequelabs/axe-cli#23]
The -a parameter doesn't work. I receive the following output:
PS C:\axe> axe -a \core\axe.js
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received true
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at Object.getAxeSource (C:\Users\aaron\AppData\Roaming\npm\node_modules\axe-cli\lib\utils.js:49:18)
    at Object.<anonymous> (C:\Users\aaron\AppData\Roaming\npm\node_modules\axe-cli\index.js:27:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
PS C:\axe>

Simple debug shows that the -a parameter is being parsed as a BOOLEAN instead of a string.

**Comment by marcysutton** [comment]
@WilcoFiers this isn't documented but it's in the source code, we should make sure it works (and is documented)

**Comment by WilcoFiers** [comment]
Not sure how that happened. I don't think I ever intended to keep that code in, but it's there now, and not hard to build, so, there you go :D

https://github.com/dequelabs/axe-cli/pull/25/

**Comment by marcysutton** [comment]
This should be fixed with #25.
