### ISSUE TITLE
Discuss extending the script timeout for larger sites

### ISSUE THREAD

**Issue by marcysutton** [dequelabs/axe-cli#4]
Chromedriver in particular has trouble testing larger sites with lots of issues, like cnn.com, without extending the driver script timeout. I'm sure folks will run into this a lot, so we should consider handling this case. I get this with Chromedriver 2.2.5.

```
02:06 PM /Users/marcysutton/Sites/Deque/axe-cli (master *+$=)> node index.js cnn.com -b chrome
Running axe-core 2.0.7 in chrome

Testing http://cnn.com ... please wait, this may take a minute.
{ ScriptTimeoutError: asynchronous script timeout: result was not received in 0 seconds
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.5 x86_64)
    at WebDriverError (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/error.js:27:5)
    at ScriptTimeoutError (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/error.js:203:5)
    at Object.checkLegacyResponse (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.executeScript()
    at thenableWebDriverProxy.schedule (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at thenableWebDriverProxy.executeAsyncScript (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/webdriver.js:900:17)
    at /Users/marcysutton/Sites/Deque/axe-cli/node_modules/axe-webdriverjs/lib/index.js:94:5
    at /Users/marcysutton/Sites/Deque/axe-cli/node_modules/axe-webdriverjs/lib/inject.js:85:5
    at ManagedPromise.invokeCallback_ (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7) name: 'ScriptTimeoutError' }
Error: "asynchronous script timeout: result was not received in 0 seconds\n  (Session info: chrome=54.0.2840.98)\n  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.5 x86_64)"
 $s ScriptTimeoutError: asynchronous script timeout: result was not received in 0 seconds
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.5 x86_64)
    at WebDriverError (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/error.js:27:5)
    at ScriptTimeoutError (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/error.js:203:5)
    at Object.checkLegacyResponse (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.executeScript()
    at thenableWebDriverProxy.schedule (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at thenableWebDriverProxy.executeAsyncScript (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/webdriver.js:900:17)
    at /Users/marcysutton/Sites/Deque/axe-cli/node_modules/axe-webdriverjs/lib/index.js:94:5
    at /Users/marcysutton/Sites/Deque/axe-cli/node_modules/axe-webdriverjs/lib/inject.js:85:5
    at ManagedPromise.invokeCallback_ (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by dylanb** [comment]
Makes sense to extend it also makes sense to document how a caller can do this themselves.
