### ISSUE TITLE
axe cmd not working post update

### ISSUE THREAD

**Issue by AkshanshSrivastava03** [dequelabs/axe-cli#55]
I am getting this error post update for each URL I am trying.

axe "https://www.google.com"
Running axe-core 2.6.0 in chrome-headless
[0329/153226.884:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
[0329/153226.885:ERROR:service_manager.cc(890)] Failed to resolve service name: metrics

DevTools listening on ws://127.0.0.1:12748/devtools/browser/22deb4b5-1dcb-4e41-ab06-db02d5956632
[0329/153228.913:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
[0329/153228.913:ERROR:service_manager.cc(890)] Failed to resolve service name: metrics
[0329/153229.084:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process.
[0329/153229.085:ERROR:gpu_process_transport_factory.cc(1009)] Lost UI shared context.

**Comment by WilcoFiers** [comment]
Runs fine for me... What version are you using, and also what platform? Is it just headless Chrome or are all browsers affected?

**Comment by AkshanshSrivastava03** [comment]
I am using the latest version available on npm (3.0.0) on Windows 10. I found this issue - https://github.com/GoogleChrome/puppeteer/issues/1610 which looks like the issue I am facing.

**Comment by WilcoFiers** [comment]
Ok, tried this with Windows 10 with Node 8.9 and still aren't able to reproduce the issue. Can you make sure your browser, driver and nodejs are up to date, and than provide us with steps to reproduce the issue?

**Comment by AkshanshSrivastava03** [comment]
Repro steps:
1.) Install axe-cli
2.) Install chrome driver (latest)
3.) Set chrome driver exe to PATH
4.) Run axe www.google.com

Running axe-core 2.6.0 in chrome-headless
[0409/122529.245:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:12468/devtools/browser/2af59bca-f64f-4e34-9c9c-fa4d78ef9340
C:\Users\aksriv\AppData\Roaming\npm\node_modules\axe-cli\node_modules\selenium-webdriver\lib\promise.js:2626
        throw error;
        ^

WebDriverError: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.16299 x86_64)
    at Object.checkLegacyResponse (C:\Users\aksriv\AppData\Roaming\npm\node_modules\axe-cli\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\aksriv\AppData\Roaming\npm\node_modules\axe-cli\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\aksriv\AppData\Roaming\npm\node_modules\axe-cli\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\aksriv\AppData\Roaming\npm\node_modules\axe-cli\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\aksriv\AppData\Roaming\npm\node_modules\axe-cli\node_modules\selenium-webdriver\chrome.js:761:15)
    at createDriver (C:\Users\aksriv\AppData\Roaming\npm\node_modules\axe-cli\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\aksriv\AppData\Roaming\npm\node_modules\axe-cli\node_modules\selenium-webdriver\index.js:642:16)
    at startDriver (C:\Users\aksriv\AppData\Roaming\npm\node_modules\axe-cli\lib\webdriver.js:33:27)
    at testPages (C:\Users\aksriv\AppData\Roaming\npm\node_modules\axe-cli\lib\axe-test-urls.js:11:10)
    at Object.<anonymous> (C:\Users\aksriv\AppData\Roaming\npm\node_modules\axe-cli\index.js:73:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)

**Comment by AkshanshSrivastava03** [comment]
Also, I tried using chrome browser directly but got no luck with that too. Chrome opens up but it crashes. What am I doing wrong here?
Also, How can I just use the phantom.js instead of chrome as I remember it used to work correctly for phantom

**Comment by WilcoFiers** [comment]
I'm not sure... I've followed those steps on a Win 10 machine and I'm not seeing any issues. What jumps out at me from your stack is the following:

> at Object.checkLegacyResponse (C:\Users\aksriv\AppData\Roaming\npm\node_modules\axe-cli\node_modules\selenium-webdriver\lib\error.js:546:15)
> at parseHttpResponse (C:\Users\aksriv\AppData\Roaming\npm\node_modules\axe-cli\node_modules\selenium-webdriver\lib\http.js:509:13)

It looks like something is breaking when trying to connect to Selenium. That's not something axe-cli has much of anything to do with, so I don't think this is something that we can resolve. You can try running using Firefox, see if that makes a difference. If that doesn't help, try installing it locally (just don't do -g when installing). You can run it with `npx axe ...` if you're using NPM 5.2+. If that gives you the same result, please send me the package lock file, that way we'll be able to exactly reproduce the setup you have.

**Comment by stephenmathieson** [comment]
Any updates here? @AkshanshSrivastava03 are you still seeing this error?

**Comment by stephenmathieson** [comment]
Closing due to inactivity
