### ISSUE TITLE
Crash when running 

### ISSUE THREAD

**Issue by SteveALee** [dequelabs/axe-cli#85]
1st time I try the cli I get boom on exit. 
I do get good results 1st though so low priority. Just looks messy.

This looks like a problem in npx cleanup - doesn axe-cli or the chromedriver do anyhting odd on exit?

`
npx axe-cli https://southwestcommunities.co.uk
`

```bash
fs.js:115
    throw err;
    ^

Error: EPERM: operation not permitted, unlink 'C:\Users\steve\AppData\Roaming\npm-cache\_npx\7288\node_modules\axe-cli\node_modules\chromedriver\lib\chromedriver\chromedriver.exe'
    at Object.unlinkSync (fs.js:949:3)
    at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:211:13)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:311:28)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:334:7)
    at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:209:5)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:311:28)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:342:5
```

**Comment by SteveALee** [comment]
Ok, so that is indeed the problem - shame

`npx --package axe-cli axe https://southwestcommunities.co.uk`

causes no error.

I'll close as I doubt you'll concider changing the command to match the package (I understand the reason)
